name: Node.js CI
on:
  pull_request:
    branches: [ "master" ]
  push:

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      YARN_IGNORE_NODE: 1

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:

      - name: 'Checkout the repository'
        uses: actions/checkout@v4

      - name: Test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Install dependencies
        run: yarn build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: yarn run test
